namespace VaultSharp.V1.SecretsEngines.TOTP
{
    /// <summary>
    /// Specifies that the key should be generated by Vault.
    /// </summary>
    public class TOTPVaultBasedKeyGeneration : AbstractTOTPKeyGenerationOption
    {
        /// <summary>
        ///  Specifies if a QR code and url are returned upon generating a key. 
        /// </summary>
        public bool Exported { get; set; }

        /// <summary>
        /// Specifies the size in bytes of the Vault generated key.
        /// </summary>
        public int KeySize { get; set; }

        /// <summary>
        /// Specifies the number of delay periods that are allowed when validating a TOTP code. 
        /// This value can be either 0 or 1.
        /// </summary>
        public int Skew { get; set; }

        /// <summary>
        /// Specifies the pixel size of the square QR code when generating a new key.
        /// Only used if and exported is true. 
        /// If this value is 0, a QR code will not be returned.
        /// </summary>
        public int QRSize { get; set; }

        public TOTPVaultBasedKeyGeneration()
        {
            Exported = true;
            KeySize = 20;
            Skew = 1;
            QRSize = 200;
        }
    }
}