<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <SignAssembly>true</SignAssembly>
    <DelaySign>false</DelaySign>
    <AssemblyOriginatorKeyFile>VaultSharp.snk</AssemblyOriginatorKeyFile>
    <PackageId>Wws.VaultSharp</PackageId>
    <Title>VaultSharp</Title>
    <Version>1.17.5.3</Version>
    <Authors>Raja Nadar</Authors>
    <Copyright>Copyright ©  2021 Raja Nadar. All rights reserved.</Copyright>
    <PackageProjectUrl>https://github.com/rajanadar/VaultSharp</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rajanadar/VaultSharp</RepositoryUrl>
    <PackageTags>c# vault hashicorp .net netcore netstandard api secret consul kv ldap aws ec2 iam userpass</PackageTags>
    <PackageReleaseNotes>https://github.com/rajanadar/VaultSharp/blob/master/CHANGELOG.md</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>
      The most comprehensive .NET Library for HashiCorp's Vault which is a modern secret management system.      

      * VaultSharp supports all Auth methods, all Secrets Engines and most System Apis supported by Vault.
      * VaultSharp  has first class support for Consul and Enterpise Vault APIs etc.
      * Enterprise APIs like Control Groups, Transform Secrets Engine &amp; KMIP Secrets Engine etc.

      This library is built with .NET 7 and hence is cross-platform across .NET Core 1.x, 2.x, 3.x, .NET Frameworks 4.x, Xamarin iOS, Android, Mac, UWP etc.
    </Description>
    <RepositoryType>Github</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>1.17.5.3</AssemblyVersion>
    <FileVersion>1.17.5.3</FileVersion>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageIcon>icon.png</PackageIcon>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    
    <!-- SourceLink specific details: https://github.com/dotnet/sourcelink/blob/master/README.md -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>

    <Deterministic>True</Deterministic>
    <ContinousIntegrationBuild>True</ContinousIntegrationBuild>
    <WarningsAsErrors>CA2007</WarningsAsErrors>
    <!-- CA2007:Do not directly await a Task - -->

  </PropertyGroup>

  <ItemGroup>
    <EmbeddedFiles Include="$(GeneratedAssemblyInfoFile)" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Common\**" />
    <EmbeddedResource Remove="Common\**" />
    <None Remove="Common\**" />
    <None Include="..\..\icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net7.0'">
    <AssemblyTitle>VaultSharp .NET 7</AssemblyTitle>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0|AnyCPU'">
    <WarningLevel>5</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0|AnyCPU'">
    <WarningLevel>5</WarningLevel>
  </PropertyGroup>

</Project>
