using System.Collections.Generic;
using Newtonsoft.Json;

namespace VaultSharp.V1.AuthMethods.AppRole.Models
{
    /// <summary>
    /// https://developer.hashicorp.com/vault/api-docs/auth/approle#generate-new-secret-id
    /// </summary>
    public class PullSecretIdRequestOptions
    {
        /// <summary>
        /// Metadata to be tied to the SecretID. 
        /// This should be a JSON-formatted string containing the metadata in 
        /// key-value pairs. This metadata will be set on tokens issued with 
        /// this SecretID, and is logged in audit logs in plaintext.
        /// </summary>
        [JsonProperty("metadata")]
        public string Metadata { get; set; }

        /// <summary>
        /// Comma separated string or list of CIDR blocks enforcing secret IDs 
        /// to be used from specific set of IP addresses. If 
        /// secret_id_bound_cidrs is set on the role, then the list of CIDR 
        /// blocks listed here should be a subset of the CIDR blocks listed on
        /// the role.
        /// </summary>
        [JsonProperty("cidr_list")]
        public List<string> CIDRList { get; set; }

        /// <summary>
        /// Comma-separated string or list of CIDR blocks; if set, specifies 
        /// blocks of IP addresses which can use the auth tokens generated by 
        /// this SecretID. Overrides any role-set value but must be a subset.
        /// </summary>
        [JsonProperty("token_bound_cidrs")]
        public List<string> TokenBoundCIDRs { get; set; }

        /// <summary>
        /// Number of times this SecretID can be used, after which the SecretID
        /// expires. A value of zero will allow unlimited uses. Overrides 
        /// secret_id_num_uses role option when supplied. May not be higher 
        /// than role's secret_id_num_uses.
        /// </summary>
        [JsonProperty("num_uses")]
        public int NumberOfUses { get; set; }

        /// <summary>
        /// Duration in seconds (3600) or an integer time unit (60m) after 
        /// which this SecretID expires. A value of zero will allow the 
        /// SecretID to not expire. Overrides secret_id_ttl role option when 
        /// supplied. May not be longer than role's secret_id_ttl.
        /// </summary>
        [JsonProperty("ttl")]
        public int TimeToLive { get; set; }        
    }
}
