namespace VaultSharp.Backends.Secret.Models.SSH
{
    /// <summary>
    /// Represents the OTP SSH Key Type Role definition.
    /// </summary>
    public class SSHOTPRoleDefinition : SSHRoleDefinition
    {
        /// <summary>
        /// <para>[required]</para>
        /// Type of credentials generated by this role.
        /// </summary>
        /// <value>
        /// The type of the key.
        /// </value>
        public override SSHKeyType KeyTypeToGenerate
        {
            get { return SSHKeyType.otp; }
        }
    }
}