using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace VaultSharp.Core
{
#if NET8_0_OR_GREATER
    [JsonSourceGenerationOptions(
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        PropertyNamingPolicy = JsonKnownNamingPolicy.Unspecified)]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.ACLPolicy>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.ActiveDirectory.ActiveDirectoryCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.ActiveDirectory.Models.ActiveDirectoryRoleModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.AliCloud.AliCloudCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.AliCloud.Models.AliCloudRoleModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.AppRole.Models.AppRolePoliciesModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.AppRole.Models.AppRoleRoleModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.AuditHash>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.Commons.AuthInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.AWS.AWSCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.AWS.AWSLeaseConfigModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.AWS.AWSRoleModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Azure.AzureCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.Core.BackendConfig>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.BackupKeyResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<bool>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.CacheResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.Token.Models.CallingTokenInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.CertificateCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.CertificateData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.CertificateKeys>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.CertificateTidyStatus>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.ActiveDirectory.Models.CheckedInAccounts>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.ActiveDirectory.Models.CheckedOutCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.Token.Models.ClientTokenInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.ActiveDirectory.Models.ConnectionConfigModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.ActiveDirectory.Models.ConnectionConfigModel), TypeInfoPropertyName = "ActiveDirectoryConnectionConfigModel")]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Database.Models.ConnectionModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Consul.ConsulCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Consul.Models.ConsulRoleModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.Enterprise.ControlGroup>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.Enterprise.ControlGroupRequestStatus>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.CORSConfig>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Identity.CreateEntityResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.Commons.CurrentSecretMetadata>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.DataKeyResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Enterprise.Transform.DecodedResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.DecryptionResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<Dictionary<string, VaultSharp.V1.SystemBackend.AbstractAuditBackend>>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<Dictionary<string, VaultSharp.V1.AuthMethods.AuthMethod>>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<Dictionary<string, Dictionary<string, bool>>>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<Dictionary<string, Dictionary<string, Dictionary<string, bool>>>>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<Dictionary<string, object>>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<Dictionary<string, VaultSharp.V1.SecretsEngines.SecretsEngine>>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.OpenLDAP.DynamicRole>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.Enterprise.EGPPolicy>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Enterprise.Transform.EncodedResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.EncryptionKeyInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.EncryptionKeyStatus>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.EncryptionResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Identity.Entity>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.ExportedKeyInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.AppRole.Models.FullSecretIdInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.Commons.FullSecretMetadata>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.GoogleCloud.GoogleCloudOAuth2Token>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.GoogleCloud.GoogleCloudServiceAccountKey>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.HashResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.HmacResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Identity.IdentityToken>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<JsonObject>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Enterprise.KeyManagement.KeyManagementKey>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Enterprise.KeyManagement.KeyManagementKMSKey>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.KeyValue.V2.KeyValue2ConfigModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Enterprise.KMIP.KMIPCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Kubernetes.KubernetesCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.OpenLDAP.LDAPCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.Lease>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.Enterprise.License>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<List<string>>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Identity.ListEntitiesResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.Commons.ListInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.Token.ListTokenRoles>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.MongoDBAtlas.MongoDBAtlasCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Nomad.NomadCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<object>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.JWT.Models.OIDCAuthURLInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.Okta.OktaVerifyPushChallengeResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.Plugin.PluginConfig>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.Policy>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.RabbitMQ.RabbitMQRole>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.RandomBytesResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.RawCertificateData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.GoogleCloudKMS.ReEncryptionResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.RekeyBackupInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.RenewedLease>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.RevokeCertificateResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.Enterprise.RGPPolicy>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Database.Role>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.AppRole.Models.RoleIdInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.AliCloud.Models.RootCredentialsConfigModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.AWS.RootIAMCredentialsConfigModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.AWS.RotateRootIAMCredentialsResponseModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.Commons.SecretData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.AppRole.Models.SecretIdInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.SecretsEngine>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.Commons.SecretSubkeysInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.ActiveDirectory.Models.ServiceAccountSetModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.GoogleCloudKMS.SignatureResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.SignedCertificateData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.SSH.SignedKeyResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.SigningResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.SSH.SSHCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Database.StaticCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Database.StaticRole>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.TerraformCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.TokenCapability>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.AuthMethods.Token.Models.TokenRoleInfo>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SystemBackend.TokenWrapData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.TOTP.TOTPCode>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.TOTP.TOTPCodeValidity>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.TOTP.TOTPCreateKeyResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.TOTP.TOTPKey>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.TransitWrappingKeyModel>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Identity.UpdateEntityResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.UsernamePasswordCredentials>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.GoogleCloudKMS.VerificationResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.Transit.VerifyResponse>))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.HealthStatus))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.Leader))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.MasterCredentials))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.ReadNamedKeyResponse))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.ReadRoleResponse))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.RekeyProgress))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.RekeyStatus))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.RootTokenGenerationStatus))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.SealStatus))]
    [JsonSerializable(typeof(JsonObject))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.FileAuditBackend))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.SyslogAuditBackend))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.CustomAuditBackend))]
    [JsonSerializable(typeof(Dictionary<string, object>))]
    [JsonSerializable(typeof(Dictionary<string, string>))]
    [JsonSerializable(typeof(List<VaultSharp.V1.SecretsEngines.AliCloud.Models.AliCloudRemotePolicyModel>))]
    [JsonSerializable(typeof(List<VaultSharp.V1.SecretsEngines.AliCloud.Models.AliCloudInlinePolicyModel>))]
    [JsonSerializable(typeof(TokenRequest))]
    [JsonSerializable(typeof(TokenClientIdRequest))]
    [JsonSerializable(typeof(InputRequest))]
    [JsonSerializable(typeof(PathTokenRequest))]
    [JsonSerializable(typeof(PathAccessorRequest))]
    [JsonSerializable(typeof(PathRequest))]
    [JsonSerializable(typeof(OtpPgpKeyRequest))]
    [JsonSerializable(typeof(KeyNonceRequest))]
    [JsonSerializable(typeof(ValueRequest))]
    [JsonSerializable(typeof(RekeyInitRequest))]
    [JsonSerializable(typeof(KeyResetRequest))]
    [JsonSerializable(typeof(MaxTtlRequest))]
    [JsonSerializable(typeof(AccessorRequest))]
    [JsonSerializable(typeof(CodeRequest))]
    [JsonSerializable(typeof(IpUsernameRequest))]
    [JsonSerializable(typeof(SerialNumberRequest))]
    [JsonSerializable(typeof(CasRequest))]
    [JsonSerializable(typeof(VersionsRequest))]
    [JsonSerializable(typeof(FormatRequest))]
    [JsonSerializable(typeof(TtlRequest))]
    [JsonSerializable(typeof(ServiceAccountNamesRequest))]
    [JsonSerializable(typeof(IncrementRequest))]
    [JsonSerializable(typeof(PoliciesRequest))]
    [JsonSerializable(typeof(PoliciesGroupsRequest))]
    [JsonSerializable(typeof(NameRequest))]
    [JsonSerializable(typeof(SecretIdRequest))]
    [JsonSerializable(typeof(SecretIdAccessorRequest))]
    [JsonSerializable(typeof(SecretIdNumUsesRequest))]
    [JsonSerializable(typeof(SecretIdTtlRequest))]
    [JsonSerializable(typeof(TokenTtlRequest))]
    [JsonSerializable(typeof(TokenMaxTtlRequest))]
    [JsonSerializable(typeof(BindSecretIdRequest))]
    [JsonSerializable(typeof(SecretIdBoundCidrsRequest))]
    [JsonSerializable(typeof(TokenBoundCidrsRequest))]
    [JsonSerializable(typeof(TokenPeriodRequest))]
    [JsonSerializable(typeof(HmacRequest))]
    [JsonSerializable(typeof(LeaseIdRequest))]
    [JsonSerializable(typeof(LeaseRenewRequest))]
    [JsonSerializable(typeof(LevelRequest))]
    [JsonSerializable(typeof(RulesRequest))]
    [JsonSerializable(typeof(PolicyTextRequest))]
    [JsonSerializable(typeof(CloudFoundryLoginRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.AbstractAuditBackend))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.AuthMethod))]
    [JsonSerializable(typeof(VaultSharp.Core.BackendConfig))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.SecretsEngine))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.CORSConfig))]
    [JsonSerializable(typeof(VaultSharp.V1.SystemBackend.InitOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.KeyValue.V2.KeyValue2ConfigModel))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.KeyValue.V2.PatchSecretDataRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.KeyValue.V2.CustomMetadataRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.AppRole.Models.AppRoleRoleModel))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.AppRole.Models.RoleIdInfo))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.AppRole.Models.PullSecretIdRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.AppRole.Models.PushSecretIdRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Database.Models.ConnectionConfigModel), TypeInfoPropertyName = "DatabaseConnectionConfigModel")]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Database.Role))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Database.StaticRole))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.CreateKeyRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.UpdateKeyRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.EncryptRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.DecryptRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.RewrapRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.DataKeyRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.SignRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.VerifyRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.HashRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.HmacRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.RandomBytesRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.TrimKeyRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.ImportKeyRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.ImportKeyVersionRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.RestoreKeyRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Transit.CacheConfigRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.CertificateCredentialsRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.SignCertificatesRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.CertificateAutoTidyRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.SSH.SignKeyRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.TOTP.TOTPCreateKeyRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.RabbitMQ.RabbitMQRole))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Consul.Models.CreateConsulRoleModel))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.AWS.CreateAWSRoleModel))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.AliCloud.Models.CreateAliCloudRoleModel))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.ActiveDirectory.Models.CreateActiveDirectoryRoleModel))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.ActiveDirectory.Models.CreateServiceAccountSetModel))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.Token.CreateTokenRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.Token.CreateTokenRoleRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.CreateEntityRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.UpdateEntityRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.CreateEntityByNameRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.UpdateEntityByNameRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.MergeEntitiesRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.BatchDeleteEntitiesRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.CreateNamedKeyRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Identity.CreateRoleRequest))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Enterprise.Transform.EncodeRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.Enterprise.Transform.DecodeRequestOptions))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.AWS.AbstractAWSAuthMethodInfo))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.AliCloud.AliCloudAuthMethodInfo))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.Azure.AzureAuthMethodInfo))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.GoogleCloud.GoogleCloudAuthMethodInfo))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.JWT.JWTAuthMethodInfo))]
    [JsonSerializable(typeof(VaultSharp.V1.AuthMethods.Kubernetes.KubernetesAuthMethodInfo))]
    // PKI Issuers
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Issuers.KeysData>), TypeInfoPropertyName = "SecretPKIIssuersKeysData")]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Issuers.IssuerResponseData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Issuers.IssuerConfigResponseData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Issuers.IssuerData>))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Issuers.IssuerData))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Issuers.IssuerConfigRequestData))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Issuers.IssuerConfigResponseData))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Issuers.IssuerResponseData))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Issuers.KeysData), TypeInfoPropertyName = "PKIIssuersKeysData")]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Issuers.KeyInfo), TypeInfoPropertyName = "PKIIssuersKeyInfo")]
    [JsonSerializable(typeof(System.Collections.Generic.Dictionary<string, VaultSharp.V1.SecretsEngines.PKI.Issuers.KeyInfo>), TypeInfoPropertyName = "DictionaryStringPKIIssuersKeyInfo")]
    // PKI Keys
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Keys.KeysData>), TypeInfoPropertyName = "SecretPKIKeysKeysData")]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Keys.KeyData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Keys.ImportKeyData>))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Keys.KeyData))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Keys.ImportKeyData))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Keys.KeysData), TypeInfoPropertyName = "PKIKeysKeysData")]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Keys.KeyInfo), TypeInfoPropertyName = "PKIKeysKeyInfo")]
    [JsonSerializable(typeof(System.Collections.Generic.Dictionary<string, VaultSharp.V1.SecretsEngines.PKI.Keys.KeyInfo>), TypeInfoPropertyName = "DictionaryStringPKIKeysKeyInfo")]
    // PKI Roles
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Roles.RolesData>))]
    [JsonSerializable(typeof(VaultSharp.V1.Commons.Secret<VaultSharp.V1.SecretsEngines.PKI.Roles.RoleData>))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Roles.RoleData))]
    [JsonSerializable(typeof(VaultSharp.V1.SecretsEngines.PKI.Roles.RolesData))]
    internal partial class VaultSharpJsonContext : JsonSerializerContext
    {
    }

#else

    // Fallback for older TFMs: a no-op resolver that always returns null,
    // causing System.Text.Json to fall back to reflection-based serialization.
    internal class VaultSharpJsonContext : IJsonTypeInfoResolver
    {
        public static VaultSharpJsonContext Default { get; } = new VaultSharpJsonContext();

        public JsonTypeInfo GetTypeInfo(Type type, JsonSerializerOptions options) => null;
    }

#endif
}
